# Numpy 맛보기

In [ ]:
import numpy as np

In [ ]:
my_list = [10, 20, 30, 40, 50]
print(my_list)
print(type(my_list))

[10, 20, 30, 40, 50]
<class 'list'>


In [ ]:
my_array = np.array(my_list)
print(my_array)
print(type(my_array))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
print(my_array.min())
print(my_array.max())
print(my_array.mean())
print(my_array.std())

10
50
30.0
14.142135623730951


In [ ]:
print(np.min(my_array))
print(np.max(my_array))
print(np.mean(my_array))
print(np.std(my_array))

10
50
30.0
14.142135623730951


# Pandas

#### Series 선언하기

In [4]:
import pandas as pd

In [5]:
my_list = [10, 20, 30, 40, 50]
my_series = pd.Series(my_list)
my_series

0    10
1    20
2    30
3    40
4    50
dtype: int64

#### Series 기능 알아보기

In [6]:
my_list = [10, 20, 30, 40, 50]
my_series = pd.Series(my_list)
my_series

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
print(my_series.values)
print(my_series.values[1])
print(my_series.values[:3])
print(my_series.values.min())
print(my_series.values.max())

[10 20 30 40 50]
20
[10 20 30]
10
50


**Series간의 연산**

In [8]:
husband_income = pd.Series(
    [300, 300, 400, 300, 300, 400, 300, 300, 400, 300, 300, 400]
)

wife_income = pd.Series(
    [400, 200, 600, 400, 200, 600, 400, 200, 600, 400, 200, 600]
)

family_income = husband_income + wife_income
family_income

0      700
1      500
2     1000
3      700
4      500
5     1000
6      700
7      500
8     1000
9      700
10     500
11    1000
dtype: int64

**Series의 모든 값에 한번에 사칙연산 적용하기**

In [67]:
husband_income + 30

0     330
1     330
2     430
3     330
4     330
5     430
6     330
7     330
8     430
9     330
10    330
11    430
dtype: int64

**Series의 모든 값에 한번에 사칙연산 적용하기**

In [68]:
husband_income = husband_income + 30
husband_income

0     330
1     330
2     430
3     330
4     330
5     430
6     330
7     330
8     430
9     330
10    330
11    430
dtype: int64

#### DataFrame 선언하기

**2차원 리스트 활용하여 선언하기**

In [9]:
my_list = [
    [10, 20, 30, 40, 50],
    [21, 31, 41, 51, 61],
    [32, 42, 52, 62, 72]
]
my_df = pd.DataFrame(my_list)
my_df

0   1   2   3   4
0  10  20  30  40  50
1  21  31  41  51  61
2  32  42  52  62  72

**Series 활용하여 선언하기**

In [10]:
income_df = pd.DataFrame([
    husband_income,
    wife_income,
    husband_income + wife_income
]).T

income_df

0    1     2
0   300  400   700
1   300  200   500
2   400  600  1000
3   300  400   700
4   300  200   500
5   400  600  1000
6   300  400   700
7   300  200   500
8   400  600  1000
9   300  400   700
10  300  200   500
11  400  600  1000

**csv 파일을 DataFrame으로 불러오기**

In [59]:
titanic = pd.read_csv("titanic.csv")

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

**excel 파일을 DataFrame으로 불러오기**

In [63]:
titanic = pd.read_excel("titanic.xlsx")

#### DataFrame 값 확인해보기

In [ ]:
print(my_df)

    0   1   2   3   4
0  10  20  30  40  50
1  21  31  41  51  61
2  32  42  52  62  72


In [ ]:
my_df

0   1   2   3   4
0  10  20  30  40  50
1  21  31  41  51  61
2  32  42  52  62  72